[package]
name = "flatgrass-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true
doctest = false

[features]
async = []

[dependencies]
proc-macro2 = "1"
quote = "1"

[dependencies.syn] 
version = "2"
features = ["full"]