use crate::parse::{EntryFn, ExitFn, LuaFn};
use proc_macro2::{Ident, Span, TokenStream};
use quote::quote;
use syn::visit_mut::VisitMut;

#[repr(transparent)]
#[derive(Debug, Clone)]
pub struct SpanVisitor(pub Span);
impl VisitMut for SpanVisitor {
	fn visit_span_mut(&mut self, span: &mut Span) {
		*span = self.0;
	}
}

pub fn generate_entry(EntryFn(lua_fn): EntryFn) -> TokenStream {
	let mut span_visitor = SpanVisitor(Span::call_site());
	let mut ident = lua_fn.0.sig.ident.clone();
	span_visitor.visit_ident_mut(&mut ident);
	let tokens = generate_func(lua_fn);

	let mixed_span = Span::mixed_site();
	let state = Ident::new("state", mixed_span);
	let lua = Ident::new("lua", mixed_span);
	let func = Ident::new("func", mixed_span);
	let res = Ident::new("res", mixed_span);
	let err = Ident::new("err", mixed_span);
	let ok = Ident::new("ok", mixed_span);

	quote! {
		#tokens

		#[doc(hidden)]
		#[unsafe(no_mangle)]
		pub unsafe extern "C-unwind" fn gmod13_open(#state: *mut ::flatgrass::ffi::lua_State) -> ::flatgrass::ffi::libc::c_int {
			use crate::{gmod13_open, gmod13_close};

			let #ok = ::flatgrass::lua::Lua::enter(#state, |#lua| {
				let #func = ::flatgrass::cfunction!(#ident);
				let #func = ::flatgrass::lua::Function::new(#func);
				#lua.__fg_entry();
				let #res = ::flatgrass::lua::call!(#func);
				match #res {
					Ok(_) => true,
					Err(#err) => {
						#lua.stack().clear();
						#lua.stack().push_any(#err);
						false
					},
				}
			});

			if !#ok {
				::flatgrass::ffi::lua_error(#state)
			} else {
				0
			}
		}
	}
}

pub fn generate_exit(ExitFn(lua_fn): ExitFn) -> TokenStream {
	let mut span_visitor = SpanVisitor(Span::call_site());
	let mut ident = lua_fn.0.sig.ident.clone();
	span_visitor.visit_ident_mut(&mut ident);
	let tokens = generate_func(lua_fn);

	let mixed_span = Span::mixed_site();
	let state = Ident::new("state", mixed_span);
	let lua = Ident::new("lua", mixed_span);
	let func = Ident::new("func", mixed_span);
	let res = Ident::new("ret", mixed_span);
	let err = Ident::new("err", mixed_span);
	let ok = Ident::new("ok", mixed_span);

	quote! {
		#tokens

		#[doc(hidden)]
		#[unsafe(no_mangle)]
		pub unsafe extern "C-unwind" fn gmod13_close(#state: *mut ::flatgrass::ffi::lua_State) -> ::flatgrass::ffi::libc::c_int {
			use crate::{gmod13_open, gmod13_close};

			let #ok = ::flatgrass::lua::Lua::enter(#state, |#lua| {
				let #func = ::flatgrass::cfunction!(#ident);
				let #func = ::flatgrass::lua::Function::new(#func);
				let #res = ::flatgrass::lua::call!(#func);
				#lua.__fg_exit();
				match #res {
					Ok(_) => true,
					Err(#err) => {
						#lua.stack().clear();
						#lua.stack().push_any(#err);
						false
					},
				}
			});

			if !#ok {
				::flatgrass::ffi::lua_error(#state)
			} else {
				0
			}
		}
	}
}

pub fn generate_func(LuaFn(item_fn): LuaFn) -> TokenStream {
	let mut span_visitor = SpanVisitor(Span::call_site());

	let vis = &item_fn.vis;
	let mut ident = item_fn.sig.ident.clone();
	span_visitor.visit_ident_mut(&mut ident);

	let mut generics = item_fn.sig.generics.clone();
	span_visitor.visit_generics_mut(&mut generics);
	let (impl_generics, type_generics, where_clause) = generics.split_for_impl();
	let generics_turbofish = type_generics.as_turbofish();

	let mixed_span = Span::mixed_site();
	let func = Ident::new("func", mixed_span);
	let state = Ident::new("state", mixed_span);
	let lua = Ident::new("lua", mixed_span);
	let arg = Ident::new("arg", mixed_span);
	let upv = Ident::new("upv", mixed_span);
	let val = Ident::new("val", mixed_span);
	let err = Ident::new("err", mixed_span);
	let res = Ident::new("res", mixed_span);
	let ret = Ident::new("ret", mixed_span);
	let n = Ident::new("n", mixed_span);

	#[rustfmt::skip]
	let args = item_fn.sig.inputs.iter().map(|_| quote! {
		match ::flatgrass::lua::FnParam::fn_param(#lua, &mut #arg, &mut #upv) {
			::core::result::Result::Ok(#val) => #val,
			::core::result::Result::Err(#err) => {
				#lua.stack().clear();
				#lua.stack().push_any(#err);
				return ::core::option::Option::None;
			}
		}
	});

	let handle_res = match &item_fn.sig.asyncness {
		Some(_) => quote! {
			#lua.async_runtime().spawn(#res).detach();
			::core::option::Option::Some(::flatgrass::lua::util::Return::Values(0))
		},
		None => quote! {
			match ::flatgrass::lua::FnReturn::fn_return(#res, #lua) {
				::core::result::Result::Ok(::flatgrass::lua::util::Return::Values(#val)) =>
					::core::option::Option::Some(::flatgrass::lua::util::Return::Values(#lua.stack().push_many(#val))),
				::core::result::Result::Ok(::flatgrass::lua::util::Return::Yield(#val)) =>
					::core::option::Option::Some(::flatgrass::lua::util::Return::Yield(#lua.stack().push_many(#val))),
				::core::result::Result::Err(#err) => {
					#lua.stack().clear();
					#lua.stack().push_any(#err);
					::core::option::Option::None
				}
			}
		},
	};

	quote! {
		#item_fn

		#[doc(hidden)]
		#[doc = "Generated by the `#[flatgrass::function]` attribute macro."]
		#vis enum #ident {}

		impl #ident {

			#[doc(hidden)]
			#[doc = ::core::concat!("Returns a raw Lua function containing glue code to call the `", ::core::stringify!(#ident), "` function from Lua.")]
			pub const fn cfunction #impl_generics () -> ::flatgrass::ffi::lua_CFunction #where_clause {
				unsafe extern "C-unwind" fn #func #impl_generics (#state: *mut ::flatgrass::ffi::lua_State) -> ::flatgrass::ffi::libc::c_int #where_clause {
					let #ret = ::flatgrass::lua::Lua::enter(#state, |#lua| {
						let (mut #arg, mut #upv) = (1, 1);
						let #res = #ident #generics_turbofish (#(#args),*);
						#handle_res
					});

					match #ret {
						::core::option::Option::None => ::flatgrass::ffi::lua_error(#state),
						::core::option::Option::Some(#ret) => match #ret {
							::flatgrass::lua::util::Return::Values(#n) => #n,
							::flatgrass::lua::util::Return::Yield(#n) => {
								::flatgrass::ffi::lua_yield(#state, #n)
							}
						}
					}
				}

				#func #generics_turbofish
			}
		}
	}
}
