use crate::parse::{EntryFn, ExitFn, LuaFn};
use proc_macro2::{Ident, Span, TokenStream};
use quote::quote;
use rspn::set_span;

pub fn generate_entry(EntryFn(lua_fn): EntryFn) -> TokenStream {
	let ident = set_span(&lua_fn.0.sig.ident, Span::call_site());
	let tokens = generate_func(lua_fn);

	let state = Ident::new("state", Span::mixed_site());
	let lua = Ident::new("lua", Span::mixed_site());
	let func = Ident::new("func", Span::mixed_site());
	let res = Ident::new("res", Span::mixed_site());
	let err = Ident::new("err", Span::mixed_site());
	let ok = Ident::new("ok", Span::mixed_site());

	quote! {
		#tokens

		#[doc(hidden)]
		#[unsafe(no_mangle)]
		pub unsafe extern "C-unwind" fn gmod13_open(#state: *mut ::flatgrass::ffi::lua_State) -> ::flatgrass::ffi::libc::c_int {
			use crate::{gmod13_open, gmod13_close};

			let #ok = ::flatgrass::lua::Lua::enter(#state, |#lua| {
				#lua.__fg_entry();
				let #func = ::flatgrass::cfunction!(#ident);
				let #func = ::flatgrass::lua::Function::new(#func);
				let #res = ::flatgrass::lua::call!(#func);
				match #res {
					Ok(_) => true,
					Err(#err) => {
						#lua.stack().clear();
						#lua.stack().push_any(#err);
						false
					},
				}
			});

			if !#ok {
				::flatgrass::ffi::lua_error(#state)
			} else {
				0
			}
		}
	}
}

pub fn generate_exit(ExitFn(lua_fn): ExitFn) -> TokenStream {
	let ident = set_span(&lua_fn.0.sig.ident, Span::call_site());
	let tokens = generate_func(lua_fn);

	let state = Ident::new("state", Span::mixed_site());
	let lua = Ident::new("lua", Span::mixed_site());
	let func = Ident::new("func", Span::mixed_site());
	let res = Ident::new("res", Span::mixed_site());
	let err = Ident::new("err", Span::mixed_site());
	let ok = Ident::new("ok", Span::mixed_site());

	quote! {
		#tokens

		#[doc(hidden)]
		#[unsafe(no_mangle)]
		pub unsafe extern "C-unwind" fn gmod13_close(#state: *mut ::flatgrass::ffi::lua_State) -> ::flatgrass::ffi::libc::c_int {
			use crate::{gmod13_open, gmod13_close};

			let #ok = ::flatgrass::lua::Lua::enter(#state, |#lua| {
				let #func = ::flatgrass::cfunction!(#ident);
				let #func = ::flatgrass::lua::Function::new(#func);
				let #res = ::flatgrass::lua::call!(#func);
				#lua.__fg_exit();
				match #res {
					Ok(_) => true,
					Err(#err) => {
						#lua.stack().clear();
						#lua.stack().push_any(#err);
						false
					},
				}
			});

			if !#ok {
				::flatgrass::ffi::lua_error(#state)
			} else {
				0
			}
		}
	}
}

pub fn generate_func(LuaFn(item_fn): LuaFn) -> TokenStream {
	let vis = set_span(&item_fn.vis, Span::call_site());
	let ident = set_span(&item_fn.sig.ident, Span::call_site());
	let generics = set_span(&item_fn.sig.generics, Span::call_site());
	let (impl_gen, type_gen, where_clause) = generics.split_for_impl();
	let turbofish = type_gen.as_turbofish();

	let func = Ident::new("func", Span::mixed_site());
	let state = Ident::new("state", Span::mixed_site());
	let lua = Ident::new("lua", Span::mixed_site());
	let arg = Ident::new("arg", Span::mixed_site());
	let upv = Ident::new("upv", Span::mixed_site());
	let val = Ident::new("val", Span::mixed_site());
	let err = Ident::new("err", Span::mixed_site());
	let res = Ident::new("res", Span::mixed_site());
	let ret = Ident::new("ret", Span::mixed_site());
	let n = Ident::new("n", Span::mixed_site());

	#[rustfmt::skip]
	let args = item_fn.sig.inputs.iter().map(|_| quote! {
		match ::flatgrass::lua::FnParam::fn_param(#lua, &mut #arg, &mut #upv) {
			::core::result::Result::Ok(#val) => #val,
			::core::result::Result::Err(#err) => {
				#lua.stack().clear();
				#lua.stack().push_any(#err);
				return ::core::option::Option::None;
			}
		}
	});

	let handle_res = match &item_fn.sig.asyncness {
		Some(_) => quote! {
			#lua.async_runtime().spawn(#res).detach();
			::core::option::Option::Some(::flatgrass::lua::util::Return::Values(0))
		},
		None => quote! {
			match ::flatgrass::lua::FnReturn::fn_return(#res, #lua) {
				::core::result::Result::Ok(::flatgrass::lua::util::Return::Values(#val)) =>
					::core::option::Option::Some(::flatgrass::lua::util::Return::Values(#lua.stack().push_many(#val))),
				::core::result::Result::Ok(::flatgrass::lua::util::Return::Yield(#val)) =>
					::core::option::Option::Some(::flatgrass::lua::util::Return::Yield(#lua.stack().push_many(#val))),
				::core::result::Result::Err(#err) => {
					#lua.stack().clear();
					#lua.stack().push_any(#err);
					::core::option::Option::None
				}
			}
		},
	};

	quote! {
		#item_fn

		#[doc(hidden)]
		#[doc = "Generated by the `#[flatgrass::function]` attribute macro."]
		#vis enum #ident {}

		impl #ident {

			#[doc(hidden)]
			#[doc = ::core::concat!("Returns a raw Lua function containing glue code to call the `", ::core::stringify!(#ident), "` function from Lua.")]
			pub const fn cfunction #impl_gen () -> ::flatgrass::ffi::lua_CFunction #where_clause {
				unsafe extern "C-unwind" fn #func #impl_gen (#state: *mut ::flatgrass::ffi::lua_State) -> ::flatgrass::ffi::libc::c_int #where_clause {
					let #ret = ::flatgrass::lua::Lua::enter(#state, |#lua| {
						let (mut #arg, mut #upv) = (1, 1);
						let #res = #ident #turbofish (#(#args),*);
						#handle_res
					});

					match #ret {
						::core::option::Option::None => ::flatgrass::ffi::lua_error(#state),
						::core::option::Option::Some(#ret) => match #ret {
							::flatgrass::lua::util::Return::Values(#n) => #n,
							::flatgrass::lua::util::Return::Yield(#n) => {
								::flatgrass::ffi::lua_yield(#state, #n)
							}
						}
					}
				}

				#func #turbofish
			}
		}
	}
}
