[package]
name = "flatgrass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.120"
libloading = "0.7.3"
once_cell = "1.0.0"

[dependencies.flatgrass-macros]
path = "../flatgrass-macros"