[package]
name = "flatgrass"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[lib]
doctest = false

[features]
serde = ["dep:serde", "either?/serde"]
either = ["dep:either"]

[dependencies]
libc = "0.2"
libloading = "0.8"

[dependencies.either]
version = "1"
optional = true

[dependencies.serde]
version = "1"
features = ["derive"]
optional = true

[dependencies.flatgrass-macros]
path = "../flatgrass-macros"

[package.metadata.docs.rs]
all-features = true
